Repository Yeri0101/sports, pull requests merged in 2022-11, with the labels that each got.

#1 Add all necessary controllers
  Gemfile.lock
  app/controllers/activities_controller.rb
  app/controllers/bookings_controller.rb
  app/controllers/reviews_controller.rb
  app/controllers/users_controller.rb
  test/controllers/activities_controller_test.rb
  test/controllers/bookings_controller_test.rb
  test/controllers/reviews_controller_test.rb
  test/controllers/users_controller_test.rb
Labels: good first issue

#2 Generate all necessary models and configure the image management system
  app/models/activity.rb
  app/models/booking.rb
  app/models/review.rb
  app/models/user.rb
  db/migrate/20221129102308_create_activities.rb
  db/migrate/20221129102615_create_bookings.rb
  db/migrate/20221129102713_create_reviews.rb
  db/migrate/20221129103030_adding_fields_to_the_users_table.rb
  db/migrate/20221129104727_create_active_storage_tables.active_storage.rb
  db/schema.rb
  test/models/activity_test.rb
  test/models/booking_test.rb
  test/models/review_test.rb
Labels: good first issue

#4 Allow a user to view an existing activity
  app/controllers/activities_controller.rb
  app/views/activities/_form.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/index.html.erb
  app/views/activities/new.html.erb
  app/views/activities/show.html.erb
Labels: enhancement

#7 Modifying the core of the application after a name change
  app/views/layouts/application.html.erb
  config/application.rb
  config/cable.yml
  config/database.yml
  config/environments/production.rb
Labels: bug

#8 Fixing the destruction of an existing activity
  app/models/activity.rb
Labels: bug

#9 Add a gem and generate random content to feed the database seeds
  Gemfile
  db/seeds.rb
Labels: enhancement

#11 Create a new migration for the activities table and generate random content to feed the database seeds
  db/migrate/20221129160630_adding_fields_to_the_activities_table.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#14 Allow a user to create a new booking
  app/controllers/bookings_controller.rb
  app/models/activity.rb
  config/routes.rb
Labels: enhancement

#15 Allow a user to delete an existing booking
  app/controllers/bookings_controller.rb
  config/routes.rb
Labels: enhancement
